version: "3"
services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - my_postgres_data:
# volumes:
#   my_postgres_data:
